### PR TITLE
fix: only insert empty block for headers and blockquote when at end of line

### PR DESCRIPTION
**Pull request by michaelgmcd**
The last PR went so well, I thought I'd keep going 👍
I found it odd when using this plugin that pressing enter at any time when within a header or blockquote block adds a new line and jumps to it. This PR ensures that the user is at the end of the line before that happens.

**Before**
\#\# He[CURSOR]ader
pressing enter becomes...
\#\# Header
[CURSOR]

\> Blockquo[CURSOR]te
pressing enter becomes...
\> Blockquote
[CURSOR]

**After**
\#\# He[CURSOR]ader
pressing enter becomes...
\#\# He
\#\# [CURSOR]ader

\> Blockquo[CURSOR]te
pressing enter becomes...
\> Blockquo
\> [CURSOR]te

I personally think this is a more intuitive behavior.

I based my knowledge of testing if we're at the end of the line from:
- https://github.com/facebook/draft-js/blob/4c4465f6c05b6dbb9eb769f98e659f917bbdc0f6/src/component/handlers/edit/commands/keyCommandMoveSelectionToEndOfBlock.js
- https://github.com/facebook/draft-js/blob/master/docs/APIReference-SelectionState.md#getendoffset

### CODE REVIEW

**Review by mxstbr — APPROVED** [review]
This makes a lot of sense to me from a behavioral perspective. Thanks so much for contributing!!

/cc @juliankrispel does this code seem right to you?

**Comment by juliankrispel** [comment]
Hey thanks for another PR 👌

We intentionally reset styles after splitting a block like header or blockquote because they are generally meant for one line only. I’d say that’s pretty typical behaviour. In fact we recently merged a pr that made sure that block styles are reset except for some that are clearly meant for multiple lines. So to be frank I don’t think this pr is in line with spectrum’s reading experience and therefore I’d say let’s not merge it.

I appreciate the effort though thank u so much. @mxstbr thoughts?

**Comment by mxstbr** [comment]
Yeah true, good point @juliankrispel—the current behavior is still a bit broken though, it should really be

## He[CURSOR]ader
pressing enter becomes...
## He
[CURSOR]ader

So it should split the text, but not preserve the block type, right? That'd be the most expected imo

**Comment by juliankrispel** [comment]
oh yes that's true - sry I overlooked that thanks for double checking @mxstbr.

Yes - that's great. Ok now the only thing we need is resetting the new block. I'll push a change momentarily - most of it is already in place - :+1:

**Comment by juliankrispel** [comment]
@mxstbr @michaelgmcd merged and follow-up pr here -> #50

**Pull request merged**
