### PR TITLE
codeblock language switch

### PR DESCRIPTION
**Pull request by juliankrispel**
So I believe we want this - a language switcher for code blocks

language switche

draft-js editors often use click events (to focus on the editor or whatever) so I'd use react-portal to display the language selection menu.

Are there any components that you guys already use or that you prefer using? It's just that there are hundreds of components like these - so any pointers as to how you'd like to have it implemented would be cool.

cc @mxstbr

### CODE REVIEW

**Comment by mxstbr** [comment]
Yeah! We use react-modal@3.x

**Comment by juliankrispel** [comment]
code-switch - ok - hab das mal so gelöst - mit einem normalen select - aber werds noch ein bisschen stylen!

**Comment by mxstbr** [comment]
Nice!! 😍

**Comment by juliankrispel** [comment]
- [x] styled the demo select
- [x] added and documented config options for rendering select and passing language options

code-switch-2

**Review by mxstbr — APPROVED** [review]
Awesome, this looks great! :100:

**Pull request merged**
