### PR TITLE
insert plain text if in code block

### LINKED ISSUE #88: Pasting code is totally broken - each line creates a new code block element
Pasting 
```js
getRawMarkup() {
    const md = new Remarkable();
    return { __html: md.render(this.state.value) };
  }
```
looks like this:
screenshot 2018-06-06 15 38 39

@mxstbr can we please hotfix this? We have lots of developer communities moving over and this is really really painful.

### PR DESCRIPTION
**Pull request by juliankrispel**
fixes #88

### CODE REVIEW

**Review by mxstbr — COMMENTED** [review]
Do we want to always just insert plain text and not try and parse markdown input? Ref #75

**Comment by juliankrispel** [comment]
@mxstbr seems like a product decision :) - the ball's in your court!

**Comment by mxstbr** [comment]
Yeah, let's avoid parsing markdown on paste and revert to the default vanilla paste behavior entirely!

**Review by mxstbr — APPROVED** [review]
I'm still going to merge this so we can release a non-breaking version with the bug fix. I'd appreciate a follow-up PR removing all this custom pasting stuff entirely! 💜

**Comment by juliankrispel** [comment]
@mxstbr I think that's the right choice tbh - converting styles on paste is a PITA ...

**Pull request merged**
