### PR TITLE
Disable inline styles inside link

### LINKED ISSUE #14: disable inline styling in links
e.g. Entering a link draft-js-linkify-plugin link with underscores in its url converts the url to a link correctly but then also switches the underscores to italic, which is no good! (This is an issue in the original plugin as well but it seems like that one isn't being maintained much these days so I thought I'd file it here. Thinking about switching over :) )

May fork and fix this myself and PR if I have time but wanted a record of the bug somewhere in case I don't have time!

### LINKED ISSUE #31: Pasting links with underscores interprets next text as italics, breaks
A bit hard to describe, so here's a video: https://www.dropbox.com/s/umssjaaoqjp7y7t/links-with-underscores.mov?dl=0

And link I was using with an underscore: https://twitter.com/brian_lovin/status/976189794022604800

### PR DESCRIPTION
**Pull request by juliankrispel**
- [x] add inLink function
- [x] add unit tests to ensure transformation is not applied when current entity is link

fixes #14 
fixes #31

### CODE REVIEW

**Review by mxstbr — APPROVED** [review]

**Comment by mxstbr** [comment]
Conflicts!

**Comment by juliankrispel** [comment]
@mxstbr solved

**Comment by Rosey** [comment]
🎉🎉

**Comment by juliankrispel** [comment]
@Rosey ayoooo ❤️

**Pull request merged**
